// SKILLS related Actions
export const FETCH_ALL_SKILLS = 'FETCH_ALL_SKILLS';
export const FETCH_LEVEL_SUBJECT = 'FETCH_LEVEL_SUBJECT';
export const FETCH_QUIZ = 'FETCH_QUIZ';
export const FETCH_PASSAGES = 'FETCH_PASSAGE'
export const FETCH_ANSWERS = 'FETCH_ANSWERS'
export const FETCH_TERM_SEARCH = 'FETCH_TERM_SEARCH'

